### ISSUE TITLE
Compile Error on OSX

### ISSUE THREAD

**Issue by hongkongkiwi** [cloudflare/boringtun#111]
Hi Guys, working on MAC OSX 10.14.5 and trying to compile I get the following errors. I'm working on the master branch.

Any ideas?

Cargo version: cargo 1.39.0 (1c6ec66d5 2019-09-30)
Installed rust using rustup-init.

`[~/boringtun]: cargo build --bin boringtun --release --target "armv7-unknown-linux-gnueabihf"`

```
   Compiling autocfg v0.1.6
   Compiling libc v0.2.62
   Compiling byteorder v1.3.2
   Compiling bitflags v1.1.0
   Compiling unicode-width v0.1.6
   Compiling safemem v0.3.2
   Compiling boxfnonce v0.1.1
   Compiling strsim v0.8.0
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `unicode-width`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `boxfnonce`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `strsim`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `safemem`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by vkrasnov** [comment]
Some of the dependencies do not support cross platform compilation. You can only compile for iOS and for Android if you have the Android SDK installed. To compile for Linux, you'd have to use Linux.

**Comment by xsoheilalizadeh** [comment]
Same issue on Ubuntu 18.04

```
Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Bren2010** [comment]
The platform would need to be "armv7-unknown-linux-gnueabihf" specifically if that's what you want to compile for. We have aarch64 and armv7 builds in CI and those work as expected.
